from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

from pydantic import BaseModel, Field

from agentic_trader.constants import AssetClass


if TYPE_CHECKING:
    from agentic_trader.config import AppConfig
    from agentic_trader.data.market_data import ContractMarketData


def clamp01(value: float) -> float:
    """Clamp a value to [0, 1], treating NaN as 0.0."""
    if value != value:  # noqa: PLR0124 -- NaN check
        return 0.0
    return max(0.0, min(1.0, float(value)))


class ScreenerCandidate(BaseModel):
    """Candidate trade setup generated by quantitative screeners and strategy evaluations."""

    contract: str
    symbol: str = Field(default="")
    asset_class: AssetClass = Field(default=AssetClass.FUTURES)
    timeframe: str
    strategy: str
    direction: str
    current_price: float
    ema_20: float
    ema_50: float
    ema_200: float
    rsi_14: float
    atr_14: float
    candle_timestamp: str
    recent_swing_low: float
    recent_swing_high: float
    trigger_detail: str
    alpha_version: str | None = None
    alpha_score: float | None = None
    alpha_policy: dict[str, Any] | None = None
    contributors: tuple[str, ...] = ()
    probe: bool = False
    setup_quality: float = Field(default=0.0, ge=0.0, le=1.0)

    def model_post_init(self, context: Any, /) -> None:
        if not self.symbol:
            self.symbol = self.contract


@runtime_checkable
class StrategyProtocol(Protocol):
    """Protocol defining the interface for all trading and screening strategies."""

    strategy_id: str
    display_name: str
    supported_asset_classes: tuple[AssetClass, ...] | list[AssetClass]
    default_timeframe: str

    def is_enabled(self, config: AppConfig) -> bool:
        """Check if this strategy is active according to the application configuration."""
        ...

    def evaluate(
        self,
        data: ContractMarketData,
        asset_class: AssetClass = AssetClass.FUTURES,
    ) -> list[ScreenerCandidate]:
        """Evaluate market data and return any qualified trade setup candidates."""
        ...


class BaseStrategy(ABC):
    """Abstract base class for quantitative strategies in the multi-strategy framework."""

    strategy_id: str = "base"
    display_name: str = "Base Strategy"
    supported_asset_classes: tuple[AssetClass, ...] = (
        AssetClass.FUTURES,
        AssetClass.EQUITY,
    )
    default_timeframe: str = "4h"

    def __init__(self, config: AppConfig | None = None) -> None:
        self.config = config

    def can_handle(self, asset_class: AssetClass) -> bool:
        """Return True if this strategy is valid for the specified asset class."""
        return asset_class in self.supported_asset_classes

    def is_enabled(self, config: AppConfig | None = None) -> bool:
        """Determine whether this strategy is enabled in the provided configuration."""
        return True

    @abstractmethod
    def evaluate(
        self,
        data: ContractMarketData,
        asset_class: AssetClass = AssetClass.FUTURES,
    ) -> list[ScreenerCandidate]:
        """Evaluate market data and return qualified candidates."""
        raise NotImplementedError
